# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DrmTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DrmTest

pod "GCDWebServer", "~> 3.0"
pod 'Alamofire', '~> 5.4'
pod 'AFNetworking', '~> 4.0'




  target 'DrmTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DrmTestUITests' do
    # Pods for testing
  end

end
